#!/bin/bash

# Check if $PYFILE variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable \$PYFILE is not set."
    exit 1
fi

# Run the Python script specified in $PYFILE variable
python "$PYFILE"

